### ISSUE TITLE
With columns: (auto, auto) does not respect document with columns(2, document)

### ISSUE THREAD

**Issue by KronosTheLate** [PgBiel/typst-tablex#6] opened 2023-05-01 08:19 UTC
Using auto, auto makes the table wider than the linewidth for a 2-column layout.
![image](https://user-images.githubusercontent.com/61620837/235427824-fbb02a3b-b63e-47dd-9aad-a4ff2dec9668.png)

If I change one to a 1fr, it fills the space nicely:
![image](https://user-images.githubusercontent.com/61620837/235427841-9cbda36e-2706-4e87-ab06-7cc0673e0f6f.png)

**Comment by PgBiel** [comment] 2023-05-01 13:48
This is certainly odd. Will investigate when I can.

**Comment by PgBiel** [comment] 2023-06-09 22:04
Fixed with 77ed90054867570b3a5d15ea371ad29bf161b5b8; please confirm later if you're still getting this, and feel free to re-open the issue if so. Thanks for reporting!

As a bonus, here's a video of my discovery of the cause of this bug... you wouldn't believe my face when I found it out, haha!


https://github.com/PgBiel/typst-tablex/assets/9021226/9292724e-5785-4f69-b588-fa77c1ddef7d

**Closed by PgBiel** 2023-06-09 22:04 UTC
Labels: bug
