### ISSUE TITLE
Fill affects line strokes

### ISSUE THREAD

**Issue by rkuemon** [PgBiel/typst-tablex#68] opened 2023-09-27 20:23 UTC
As you can see below, `tablex` handles line strokes differently when a cell is filled. The same happens when using `cellx` manually. The official `table` doesn't behave that way.

```typst
#import "@preview/tablex:0.0.5": *

#table(
  columns: (auto, auto),  
  stroke: 4pt,
  fill: (col, row) => if col == 0 { luma(240) },
  [test],[test],
  [test],[test],
  [test],[test],
)

#tablex(
  columns: (auto, auto),  
  stroke: 4pt,
  fill: (col, row) => if col == 0 { luma(240) },
  [test],[test],
  [test],[test],
  [test],[test],
)
```
![grafik](https://github.com/PgBiel/typst-tablex/assets/125966213/c5cb4422-9445-4652-bcf4-21c548e26b87)

**Comment by PgBiel** [comment] 2023-09-27 21:12
Duplicate of #4.

**Closed by PgBiel** 2023-09-27 21:12 UTC
