### ISSUE TITLE
Tables can overrun the right margin

### ISSUE THREAD

**Issue by wlupton** [PgBiel/typst-tablex#42] opened 2023-08-09 14:12 UTC
*I haven't yet tried to reproduce this problem in a small document. Please let me know if you'd like me to try to do this.*

Please see the beginning part of the Typst code for a table, and how it renders.
```
#figure(
  kind: table,
  caption: [Table 1: XML Description Markup])[
  #tablex(
    columns: (auto, auto, auto),
    align: (auto, auto, auto),
    fill: table-fill.with(columns: 3, header-rows: 1),
    header-rows: 1,
    repeat-header: true,
    header-hlines-have-priority: false,
    auto-hlines: true,
    auto-vlines: false,
    (), vlinex(), vlinex(), (),
    [Name], [Markup Example], [Description],
    [Italics], [`''italic text''`], [Two apostrophes on each side of
      some text will result in the contained text being emphasized in
      italics.],
    [Bold], [`'''bold text'''`], [Three apostrophes on each side of some
      text will result in the contained text being emphasized in bold.],
    [Bold italics], [`'''''b+i text'''''`], [Five apostrophes on each
      side of some text will result in the contained text being
      emphasized in bold italics.],
    [Paragraph], [This paragraph just ended.], [A line break is
      interpreted as a paragraph break.],
...
```

![Screenshot 2023-08-09 at 15 11 00](https://github.com/PgBiel/typst-tablex/assets/8874729/a694065e-348d-4a95-ad3d-3adc11a725bd)

**Comment by PgBiel** [comment] 2023-08-11 17:44
Hi, I couldn't reproduce your issue, but I've pushed a fix to main which might help (with https://github.com/PgBiel/typst-tablex/commit/f00b91c7d9383ebd194fb9e36ee5999339c38891). Can you try and see if the latest version in main makes a difference in your case (possibly fixes the issue)? Maybe also share a minimal repro if possible so I can conduct my own tests. Thanks!

**Comment by PgBiel** [comment] 2023-10-20 06:20
Closing due to inactivity; feel free to reopen if the issue is still reproducible.

**Closed by PgBiel** 2023-10-20 06:20 UTC
Labels: bug
