### ISSUE TITLE
The customize cell after the first row fill color will cover a little of the top line of the cell

### ISSUE THREAD

**Issue by capvor** [PgBiel/typst-tablex#66] opened 2023-09-20 10:14 UTC
The customize cell after the first row fill color will cover a little of the top line of the cell.

```typst
#tablex(
  columns: 3,
  rows: auto,
  align: center + horizon,
  [1], [2], [3],
  [4], cellx(colspan:2, fill: rgb(82%, 90%, 100%), [5]),
  [7], [8], [9],
)
```
![image](https://github.com/PgBiel/typst-tablex/assets/16610170/862aab74-cbc4-4914-b74d-75814f72c013)

The first row couldn't
```typst
#tablex(
  columns: 3,
  rows: auto,
  align: center + horizon,
  [1], [2], cellx(fill: red, [3]),
  [4], cellx(fill: blue, [5]), [6],
  [7], [8], [9],
)
```
![image](https://github.com/PgBiel/typst-tablex/assets/16610170/11f91727-db16-4425-b66f-f761e378f404)

**Comment by PgBiel** [comment] 2023-09-20 14:00
Duplicate of #4.

**Closed by PgBiel** 2023-09-20 14:00 UTC
